version: "3.7"

services:
  base:
    build: .
    volumes:
      - conf:/etc/clamav
      - data:/var/lib/clamav

  freshclam:
    extends:
      service: base
    environment:
      MODE: freshclam

  clamav:
    extends:
      service: base
    depends_on:
      - freshclam
    environment:
      MODE: clamd
    ulimits:
      stack: 1048576
    ports:
      - "3310:3310"

volumes:
  conf:
  data:
